package pl.pkociolek.zbik.model;

public enum Permission {
  POST_VIEW_PUBLIC,
  POST_VIEW_INTERNAL,
  POST_VIEW_PRIVATE,
  POST_PUBLISH_PUBLIC,
  POST_PUBLISH_INTERNAL,
  POST_PUBLISH_PRIVATE,
  POST_EDIT_PUBLIC,
  POST_EDIT_INTERNAL,
  POST_EDIT_PRIVATE,
  POST_SELF_CREATE,
  POST_SELF_EDIT,
  POST_SELF_DELETE,
  ROLE_EDIT,
  ROLE_EDIT_PROTECTED,
  ROLE_CREATE,
  ROLE_CREATE_PROTECTED,
  ROLE_DELETE,
  ROLE_DELETE_PROTECTED
}
