spring:
  data:
    mongodb:
      host: localhost
      port: '27020'
      database: sbus
      username: admin
      password: admin
    redis:
      database: '0'
      host: localhost
      port: '16379'
      username: default
      password: admin
      timeout: '60000'
